export { default as Dashboard } from "./Dashboard";
export { default as HomeLayout } from "./HomeLayout";
export { default as Landing } from "./Landing";
export { default as Login } from "./Login";
export { default as Register } from "./Register";
export { default as Logout } from "./Logout";
//export { default as ProfilePic } from "./ProfilePic";
export { default as Videocall } from "./videocall";
export {default as Whiteboard} from './whiteboard';
export { default as Feedback } from "./Feedback";